# Generated by Django 3.2.6 on 2024-07-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
