# Generated by Django 3.2.6 on 2024-07-19 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tweet_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Ortho', 'Ortho'), ('Trauma', 'Trauma'), ('General Surygery', 'General Surygery')], max_length=100)),
                ('is_available', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(limit_choices_to={'user_type': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
