# Generated by Django 3.2.6 on 2024-07-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='speciality',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Ortho', 'Ortho'), ('Trauma', 'Trauma'), ('General Surygery', 'General Surygery')], default=None, max_length=100),
            preserve_default=False,
        ),
    ]
