# Generated by Django 3.2.6 on 2024-07-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appointment_speciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='speciality',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Ortho', 'Ortho'), ('Trauma', 'Trauma'), ('General Surgery', 'General Surgery')], max_length=100),
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='speciality',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Ortho', 'Ortho'), ('Trauma', 'Trauma'), ('General Surgery', 'General Surgery')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], default='patient', max_length=10),
        ),
    ]
