# Generated by Django 5.0.7 on 2024-07-19 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_event_alter_doctorprofile_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='is_available',
        ),
    ]
