# Generated by Django 5.0.7 on 2024-07-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_doctorprofile_is_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
