# Generated by Django 5.0.7 on 2024-07-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_delete_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='speciality',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Neurology', 'Neurology'), ('Pediatrics', 'Pediatrics'), ('Ortho', 'Ortho'), ('Trauma', 'Trauma'), ('General Surgery', 'General Surgery')], default=None, max_length=100, verbose_name='Speciality'),
            preserve_default=False,
        ),
    ]
